send_command:
  name: Send Command
  description: Send commands to Emotiva XMC-1
  fields:
    xmcCommand:
      name: XMC Command
      description: "Select the command to execute"
      required: true
      selector:
        select:
          mode: dropdown 
          options:
            - label: Volume Up
              value: "volup"
            - label: Volume Down
              value: "voldown"
            - label: Mute
              value: "mute"
            - label: Power On
              value: "poweron"
            - label: Power Off
              value: "poweroff"
            - label: Input
              value: "input"
    xmcValue:
      name: XMC Command Value
      description: "The value associated with the command"
      required: false
      selector:
        text:

discover:
  name: Discover XMC Processor
  description: Discover XMC Processors on the network and update states

update_state:
  name: Update States
  description: Update states for volume, power, mute, input etc. for XMC processor

